### ISSUE TITLE
axisMaximum and axisMinimum have not effect

### ISSUE THREAD

**Issue by minggo** [Jpadilla1/react-native-ios-charts#15]
The config data looks like:

```
return {
    barData: {
      dataSets: [{
        values: barDataValue,
        drawValues: false,
        colors: ['rgb(211,211,211)']
      }]
    },
    candleData: {
      dataSets: [{
        values: candleDataValue,
        colors: candleDataColor,
        drawValues: false
      }],
    },
    drawBarShadowEnabled: false,
    backgroundColor: 'transparent',
    labels: labels,
    showLegend: false,
    drawBorders: true,
    xAxis: {
      position: 'bottom',
      avoidFirstLastClipping: true,
      textSize: 7.5,
      gridDashedLine: {
        lineLength: 1,
        spaceLength: 1
      }
    },
    leftAxis: {
      drawLabels: false,
      drawGridLines: false,
      spaceBottom: 0,
    },
    rightAxis: {
      drawGridLines: true,
      spaceBottom: 0,
      gridDashedLine: {
        lineLength: 1,
        spaceLength: 1
      },
      axisMaximum: 1000,
      axisMinimum: 100
    },
    valueFormatter: {
      type: 'regular',
      maximumDecimalPlaces: 0
    }
  };
```

But the chart looks like
<img width="370" alt="screen shot 2016-04-07 at 10 54 14 pm" src="https://cloud.githubusercontent.com/assets/488203/14355734/a1ba9452-fd14-11e5-91d2-25a781c6371e.png">

As you can see, the max value and min value is not 1000 and 100.

**Comment by carlos-wong** [comment]
try startAtZero:false

**Comment by minggo** [comment]
@carlos-wong Thanks for the answer, i will try it.

**Comment by minggo** [comment]
@carlos-wong `startAtZero:false` can not resolve it.

**Comment by minggo** [comment]
@Jpadilla1 Could you please take a look?
Thanks.

**Comment by Jpadilla1** [comment]
@carlos-wong Sure, I take a look at it today.

**Comment by minggo** [comment]
Thanks.

**Comment by Jpadilla1** [comment]
Hi @minggo this should be fixed in the latest release `0.2.2`. The problem was that the values were being set to `axisMaximum` & `axisMinimum` when it should be set to `customAxisMax` & `customAxisMin`. Let me know if it works for you!

**Comment by minggo** [comment]
@Jpadilla1 Thanks. 
But i didn't found `0.2.2`, is it released? Because it use `pod install` to update dependences, it is not convenient for me to test i in my lib. Or could you share me the pull request, than i can do the modification myself.

**Comment by minggo** [comment]
@Jpadilla1 It seems it is not fixed, the config data is:

```
return {
    barData: {
      dataSets: [{
        values: barDataValue,
        drawValues: false,
        colors: ['rgb(211,211,211)'],
        axisDependency: 'left'
      }]
    },
    candleData: {
      dataSets: [{
        values: candleDataValue,
        colors: candleDataColor,
        drawValues: false,
        highlightEnabled: true,
        axisDependency: 'right'
      }],
    },
    drawBarShadowEnabled: false,
    backgroundColor: 'transparent',
    labels: labels,
    showLegend: false,
    drawBorders: true,
    xAxis: {
      position: 'bottom',
      avoidFirstLastClipping: true,
      gridDashedLine: {
        lineLength: 1,
        spaceLength: 1
      }
    },
    leftAxis: {
      drawLabels: false,
      drawGridLines: false,
      spaceBottom: 0,
      // axisMaximum: biggestVolume * 1.5,
      // axisMinimum: smallestVolume
    },
    rightAxis: {
      drawGridLines: true,
      spaceBottom: 0,
      gridDashedLine: {
        lineLength: 1,
        spaceLength: 1
      },
      axisMaximum: 1000,
      axisMinimum: 100
    },
    valueFormatter: {
      type: 'regular',
      maximumDecimalPlaces: decimalPlaces,
      minimumDecimalPlaces: decimalPlaces
    }
  };
}
```

the effect is

<img width="380" alt="screen shot 2016-04-11 at 4 19 53 pm" src="https://cloud.githubusercontent.com/assets/488203/14420941/6dd27ef8-0001-11e6-8e18-06a776679ebe.png">

**Comment by Jpadilla1** [comment]
@minggo you are right, I missed a few changes in the last release (0.2.2), so I included them in 0.2.3.

``` javascript
const config = {
  barData: {
    dataSets: [{
      values: [1000, 2000, 5000, 10000, 8000, 6000, 4000],
      drawValues: false,
      colors: ['rgb(211,211,211)'],
      axisDependency: 'right'
    }]
  },
  candleData: {
    dataSets: [{
      values: [{
        shadowH: 20,
        shadowL: 5,
        open: 15,
        close: 10
      }, {
        shadowH: 30,
        shadowL: 10,
        open: 25,
        close: 15
      }, {
        shadowH: 10,
        shadowL: 5,
        open: 15,
        close: 10
      }, {
        shadowH: 50,
        shadowL: 5,
        open: 25,
        close: 15
      }],
      colors: ['red', 'green', 'red', 'green', 'red', 'green', 'red'],
      drawValues: false,
      highlightEnabled: true,
      axisDependency: 'left'
    }],
  },
  drawBarShadowEnabled: false,
  labels: ['Mar 31', 'Apr 1', 'Apr 2', 'Apr 3', 'Apr 4', 'Apr 5', 'Apr 6'],
  showLegend: false,
  drawBorders: true,
  xAxis: {
    position: 'bottom',
    avoidFirstLastClipping: true,
    gridDashedLine: {
      lineLength: 1,
      spaceLength: 1
    }
  },
  leftAxis: {
    drawLabels: false,
    drawGridLines: false,
    spaceBottom: 0
    // axisMaximum: biggestVolume * 1.5,
    // axisMinimum: smallestVolume
  },
  rightAxis: {
    drawGridLines: true,
    spaceBottom: 0,
    gridDashedLine: {
      lineLength: 1,
      spaceLength: 1
    },
    axisMaximum: 10000,
    axisMinimum: 100
  },
  valueFormatter: {
    type: 'regular',
    maximumDecimalPlaces: 2,
    minimumDecimalPlaces: 2
  }
}
```

<img width="487" alt="screen shot 2016-04-11 at 10 03 48 am" src="https://cloud.githubusercontent.com/assets/3780146/14429746/b444d442-ffcc-11e5-99d9-13a8e798fd24.png">

Here is the commit with the changes to axisMaximum & axisMinimum. 
https://github.com/Jpadilla1/react-native-ios-charts/commit/6ae0726954da789c933ee7c6c7aeebf0dd0c0d46

**Note: This does not work with the latest version of iOS-Charts (2.3.4) as they are breaking changes in that version.**

**Comment by minggo** [comment]
It works now, thanks.
